tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "pkgxdev/made"

brew "age"
brew "age-plugin-yubikey"
brew "fd"
brew "fzf"
brew "git"
brew "gh"
brew "gnu-getopt"
brew "jq"
brew "lazygit"
brew "llvm"
brew "lsd"
brew "neovim"
brew "pkgxdev/made/pkgx"
brew "pinentry-mac"
brew "qrencode"
brew "ripgrep"
brew "rustup-init"
brew "starship"
brew "tmux"
brew "tree"
brew "trezor-agent"
brew "ykman"
brew "yubikey-agent", restart_service: true
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"

cask "font-monaspace"
cask "wezterm"
